#!/usr/bin/env python3


#standard library imports
import sys 
import curses

#project files
from lox import run_prompt, run_script




def main():
    if len(sys.argv) == 1:
        run_prompt.run_prompt()
    elif len(sys.argv) == 2:
        run_script.run_script(sys.argv[1])
    else:
        print('usage : plox [script]')
        sys.exit() 

if __name__ == '__main__':
    main()